home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path('', views.index, name='home'),
    
    #ajax
    path("ajax", views.ajaxMain, name="ajaxMain"),
    path("ajax/ajax", views.ajax, name="ajax"),
    path("ajax/ajaxjq", views.ajaxjq, name="ajaxjq"),
    path("ajax/ajaxjqcsrf", views.ajaxjqcsrf, name="ajaxjqcsrf"),
    path("response/<str:letter>", views.response, name="response"),
    path("post/response", views.responsePost, name="responsePost"),

    #misc
    path("space", views.space, name="space"),
    path("download", views.download, name="download"),

    #login
    path("accounts/signUp", views.signUp, name="signUp"),
    path("check/checkNewUser", views.checkNewUser, name="checkNewUser"),

    path("accounts/logIn", views.logIn, name="logIn"),
    path("check/logInCheck", views.logInCheck, name="logInCheck"),

    path("accounts/data", views.accountData, name="accountData"),

    path("check/checkLogOut", views.logOutCheck, name="logOutCheck"),

    path("accounts/changePassword", views.changePassWord, name="changePassWord"),
    path("check/passWord", views.validateNewPassword, name="validateNewPassword"),

    path("accounts/profilePic", views.profilePic, name="profilePic"),
    path("check/addProfilePic", views.addProfilePic, name="addProfilePic"),

    path("check/changeUserDescription", views.changeUserDescription, name="changeUserDescription"),
    path("check/delete", views.deleteUser, name="deleteUser"),
    #path("check/getDescription", views.getDescription, name="getDescription"),


    #post
    path("post/postContent", views.postContent, name="postContent"),
    path("check/newPost", views.newPost, name="newPost"),

    path("post/All/", views.allPosts, name="allPosts"),
    path("post/getAll", views.getAllUserPosts, name="getAllUserPosts"),
    path("post/getLast", views.getLastPost, name="getLastPost"),

    #chat
    path("chat", views.chatAll, name="chatAll"),
    path("chat/<str:room_name>/", views.room, name="room"),

    #attack
    path("attack/csrf", views.csrfAttack, name="csrfAttack"),

    path("friends/sendFriendRequest", views.sendFriendRequest, name="sendFriendRequest"),
    path("friends/getUserList", views.getUserList, name="getUserList"),
    path("friends/friendRequest", views.friendRequest, name="friendRequest"),
    path("friends/checkFriendRequest", views.checkFriendRequest, name="checkFriendRequest"),
    path("friends/getFriendRequest", views.getFriendRequest, name="getFriendRequest"),
    path("friends/acceptFriendRequest", views.acceptFriendRequest, name="acceptFriendRequest"),
    path("friends/allMyFriends", views.allMyFriends, name="allMyFriends"),
    path("friends/getFriends", views.getFriends, name="getFriends"),
    path("friends/removeFriend", views.removeFriend, name="removeFriend"),
    path("friends/firendProfile/<str:username>", views.firendProfile, name="firendProfile"),

    #chat
    path("userChat/<str:chatId>", views.chat, name="chat"),
    path("userChat/<str:username1>/<str:username2>", views.chatFriendToFriend, name="chatFriendToFriend"),
    path("initChat/<str:chatId>", views.initChat, name="initChat"),
]

myServer1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    #app
    path("home/", include("home.urls")),
    #favicon
    path('favicon.ico/', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    #admin
    path('admin/', admin.site.urls),
]

home/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

def dAllUsers():
    for user in User.objects.all():
        user.delete()

def dAllPosts():
    for user in UserPost.objects.all():
        user.delete()

def dAllFriends():
    for user in UserFriends.objects.all():
        user.delete()

def dAllRF():
    for user in FriendRequest.objects.all():
        user.delete()

def dAllChat():
    for user in Chat.objects.all():
        user.delete()

def dAllMessage():
    for user in Message.objects.all():
        user.delete()


class User(models.Model):
    username = models.CharField(max_length=254)
    password = models.CharField(max_length=254)
    creationDate = models.DateTimeField()
    profilePic = models.FileField(upload_to="static/upload/profilePic/", default="static/upload/profilePic/default.jpg")
    description = models.CharField(max_length=254, default="There is no description here")
    friends = models.ManyToManyField("UserFriends")
    friendRequest = models.ManyToManyField("FriendRequest")    

    def delete(self):
        for friend in self.friends:
            friend.delete()

        for friendRequest in self.friendRequest:
            friendRequest.delete()
        super().delete()

    def __str__(self):
        #return f"username: {self.username}, password: {self.password}, creationDate: {self.creationDate}, description: {self.description}, profilePic: {self.profilePic.url}"
        return f"""
(
    username: {self.username}, 
    password: {self.password}, 
    creationDate: {self.creationDate}, 
    description: {self.description}, 
    profilePic: {self.profilePic.url},
    friends: {self.friends.all().values_list("username", flat=True)}
    friendRequest: {self.friendRequest.all().values_list("username", flat=True)}
)
""".replace("(", "{").replace(")", "}")


class UserFriends(models.Model):
    username = models.CharField(max_length=254)
    creationDate = models.DateTimeField()

    def __str__(self):
        return f"username: {self.username}, creationDate: {self.creationDate}"


class FriendRequest(models.Model):
    username = models.CharField(max_length=254)
    creationDate = models.DateTimeField()

    def __str__(self):
        return f"username: {self.username}, creationDate: {self.creationDate}"

    @staticmethod
    def sendFriendRequest(fromUser, toUser):
        friendCheck = User.objects.filter(username=toUser).get().friends.filter(username=fromUser)
        if friendCheck.exists():
            return "This user is already your friend"
        userTo = User.objects.filter(username=toUser)
        if userTo.exists():
            if not User.objects.filter(username=toUser).get().friendRequest.filter(username=fromUser).exists():
                userDes = userTo.get()
                friendRequest = FriendRequest(username=fromUser, creationDate=timezone.now())
                friendRequest.save()

                userDes.friendRequest.add(friendRequest)
                userDes.save()

            return "Friend request sended successfully"

        return "Username does not exists"


class UserPost(models.Model):
    username = models.CharField(max_length=254)
    content = models.CharField(max_length=254)
    creationDate = models.DateTimeField()

    def __str__(self):
        return f"""
(
    username: {self.username}, 
    content: {self.content}, 
    creationDate: {self.creationDate}
)
""".replace("(", "{").replace(")", "}")

class Chat(models.Model):
    chatId = models.CharField(max_length=508)
    messages = models.ManyToManyField("Message")
    creationDate = models.DateTimeField()

    def __str__(self):
        return f"chatId: {self.chatId}, messages: {self.messages.all()}"


class Message(models.Model):
    user = models.ManyToManyField("User")
    content = models.CharField(max_length=254)
    creationDate = models.DateTimeField()

    def __str__(self):
        return f"user: {self.user}, creationDate: {self.creationDate}, content: {self.content}"


home/views.py
import json, time
from django.shortcuts import render, redirect
from django.core.files.storage import default_storage
from django.http import HttpResponse, JsonResponse, Http404
from django.template import loader
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.utils import timezone
from django.core.files import File
from django import db
from . import urls, models, consumers

# Create your views here.

def index(request):
    template = loader.get_template("home/index.html")
    return HttpResponse(template.render())

def ajaxMain(request):
    """
    print(urls.urlpatterns)

    for patter in urls.urlpatterns:
    """
    return HttpResponse(
        render(
            request, 
            "home/ajaxMain.html",
            context={
                "myList": ["ajax", "ajaxjq", "ajaxjqcsrf", "home"]
            }
        )
    )

def ajax(request):
    template = loader.get_template("home/ajax/ajax.html")
    return HttpResponse(template.render())

@csrf_exempt
def ajaxjq(request):
    return HttpResponse(render(request, "home/ajax/ajaxjq.html"))

def ajaxjqcsrf(request):
    template = loader.get_template("home/ajax/ajaxjqcsrf.html")
    return HttpResponse(template.render())

def download(request):
    template = loader.get_template("home/download.html")
    return HttpResponse(template.render())

def space(request):
    template = loader.get_template("home/space.html")
    return HttpResponse(template.render())

def response(request, letter):
    a = list()

    a.append("Anna")
    a.append("Brittany")
    a.append("Cinderella")
    a.append("Diana")
    a.append("Eva")
    a.append("Fiona")
    a.append("Gunda")
    a.append("Hege")
    a.append("Inga")
    a.append("Johanna")
    a.append("Kitty")
    a.append("Linda")
    a.append("Nina")
    a.append("Ophelia")
    a.append("Petunia")
    a.append("Amanda")
    a.append("Raquel")
    a.append("Cindy")
    a.append("Doris")
    a.append("Eve")
    a.append("Evita")
    a.append("Sunniva")
    a.append("Tove")
    a.append("Unni")
    a.append("Violet")
    a.append("Liza")
    a.append("Elizabeth")
    a.append("Ellen")
    a.append("Wenche")
    a.append("Wendy")
    a.append("Vicky")
    a.append("Monika")
    a.append("Mariana")
    a.append("Maria")
    a.append("Martha") 

    names = list()
    for name in a:
        if name[0].lower() == letter.lower():
            names.append(name)

    return HttpResponse("no suggestion" if len(names) == 0 else ", ".join(names))

@csrf_exempt
def responsePost(request):
    a = list()

    a.append("Anna")
    a.append("Brittany")
    a.append("Cinderella")
    a.append("Diana")
    a.append("Eva")
    a.append("Fiona")
    a.append("Gunda")
    a.append("Hege")
    a.append("Inga")
    a.append("Johanna")
    a.append("Kitty")
    a.append("Linda")
    a.append("Nina")
    a.append("Ophelia")
    a.append("Petunia")
    a.append("Amanda")
    a.append("Raquel")
    a.append("Cindy")
    a.append("Doris")
    a.append("Eve")
    a.append("Evita")
    a.append("Sunniva")
    a.append("Tove")
    a.append("Unni")
    a.append("Violet")
    a.append("Liza")
    a.append("Elizabeth")
    a.append("Ellen")
    a.append("Wenche")
    a.append("Wendy")
    a.append("Vicky")
    a.append("Monika")
    a.append("Mariana")
    a.append("Maria")
    a.append("Martha") 

    names = list()
    for name in a:
        if name[0].lower() == request.POST.dict()["letter"].lower():
            names.append(name)
            
    return HttpResponse("no suggestion" if len(names) == 0 else ", ".join(names))


@csrf_exempt
def signUp(request):
    return render(request, "home/accounts/signUp.html")

@csrf_exempt
def checkNewUser(request):
    post = request.POST

    username = post.get("username")
    password = post.get("password")

    if username == "":
        return HttpResponse("Ivalid blank username")
    print("username")

    if password == "":
        return HttpResponse("Ivalid blank password")
    print("password")

    if username.replace(" ", "") == "":
        return HttpResponse("usernames cannot contain spaces")
    print("username space")

    if " " in password:
        return HttpResponse("passwords cannot contain spaces")
    print("password space")

    if models.User.objects.filter(username=username).exists():
        return HttpResponse("The username already exists")
    print("username used")

    if len(password) < 8:
        return HttpResponse("The password must be at least 8 characters long")
    print("passwordlen")

    user = models.User(username=username, password=password, creationDate=timezone.now())
    user.save()
    print("username saved")

    # no puede ser == ""
    # el nombre de usuario no debe estar usado
    # la contraseña de tener mas de 8 caracteres

    # si todo esta bien, se procede a la siguiente página

    # si algo esta mal, se devuelve que esta mal
    response = HttpResponse("True")
    response.set_cookie("username", username)
    response.set_cookie("password", password)
    return response

@csrf_exempt
def accountData(request):
    print(request.COOKIES)
    if "username" in request.COOKIES and "password" in request.COOKIES:
        user = models.User.objects.filter(username=request.COOKIES["username"])
        if user.exists():
            if user.get().password == request.COOKIES["password"]:
                return render(
                    request, 
                    "home/accounts/accountData.html", 
                    context={
                        "username": request.COOKIES["username"],
                        "password": request.COOKIES["password"],
                        "creationDate": user.get().creationDate,
                        "description": user.get().description,
                        "profilePic": user.get().profilePic.url
                    }
                )

    return redirect("home:logIn")

@csrf_exempt
def changePassWord(request):
    return render(request, "home/accounts/changePassword.html")

@csrf_exempt
def validateNewPassword(request):
    post = request.POST
    oldPassword = post.get("oldPassword")
    newPassword = post.get("newPassword")
    newPasswordCon = post.get("newPasswordCon")

    if oldPassword == "" or newPassword == "" or newPasswordCon == "":
        return HttpResponse("Ivalid blank password")

    if " " in oldPassword or " " in newPassword or " " in newPasswordCon:
        return HttpResponse("passwords cannot contain spaces")

    if len(oldPassword) < 8 or len(newPassword) < 8 or len(newPasswordCon) < 8:
        return HttpResponse("The password must be at least 8 characters long")

    if "username" in request.COOKIES and "password" in request.COOKIES:
        username = request.COOKIES["username"]
        user = models.User.objects.filter(username=username)

        if user.exists():
            if user.get().password == oldPassword:
                if newPassword == newPasswordCon:
                    userpass = user.get()
                    userpass.password = newPassword
                    userpass.save()
                    response = HttpResponse("Password changed succesfully")
                    response.set_cookie("password", newPassword)
                    return response

                return HttpResponse("The new password does not match")
            
            return HttpResponse("Invalid old password")

        return HttpResponse("The user does not exists")

    return redirect("home:logIn")

@csrf_exempt
def logIn(request):
    return render(request, "home/accounts/logIn.html")

@csrf_exempt
def logInCheck(request):
    post = request.POST

    username = post.get("username")
    password = post.get("password")

    if username == "":
        return HttpResponse("Ivalid blank username")
    print("username")

    if password == "":
        return HttpResponse("Ivalid blank password")
    print("password")

    if username.replace(" ", "") == "":
        return HttpResponse("usernames cannot contain spaces")
    print("username space")

    if " " in password:
        return HttpResponse("passwords cannot contain spaces")
    print("password space")

    if len(password) < 8:
        return HttpResponse("The password must be at least 8 characters long")
    print("passwordlen")

    user = models.User.objects.filter(username=username)
    if user.exists():
        if user.get().password == password:
            response = HttpResponse("True")
            response.set_cookie("username", username)
            response.set_cookie("password", password)
            return response

        else:
            return HttpResponse("Incorrect Password")

    else:
        return HttpResponse("The username does not exists")

def logOutCheck(request):
    response = HttpResponse("Log Out Succesfuly")
    response.delete_cookie("username")
    response.delete_cookie("password")
    return response


def deleteUser(request):
    response = redirect("home:home")
    if "username" in request.COOKIES and "password" in request.COOKIES:
        username = request.COOKIES["username"]
        password = request.COOKIES["password"]

        user = models.User.objects.filter(username=username)
        if user.exists() and user.get().password == password:
            user.delete()
            response.delete_cookie("username")
            response.delete_cookie("password")

    return response

@csrf_exempt
def csrfAttack(request):
    return render(request, "home/attac/csrf.html")

@csrf_exempt
def profilePic(request):
    return render(request, "home/accounts/profilePic.html")

@csrf_exempt
def addProfilePic(request):

home/templates/home/post/allPosts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Post</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(
            function() {

                var allPosts;
                var postContent = document.getElementById("postContent");
                $.get(
                    "{% url 'home:getAllUserPosts' %}",
                    function(data, status) {
                        if (status == "success") {
                            allPosts = eval(data);
                            for (var index in allPosts) {
                                generatePostElement(postContent, allPosts[index]["content"]);
                                getLastPost();
                            }
                        }
                    }
                )

                function getLastPost() {
                    $.get(
                        "{% url 'home:getAllLastPost' %}",
                        function(data, status) {
                            var newPost = document.getElementById("newPosts")
                            if (status == "success") {
                                post = eval(data);
                                generatePostElement(newPost, post["content"]);
                                getLastPost();
                            }
                        }
                    )
                }
                
                function generatePostElement(parent, content) {
                    var tag = document.createElement("p");
                    tag.appendChild(document.createTextNode(content));
                    parent.insertAdjacentElement("beforebegin", tag);
                    parent.insertAdjacentElement("beforebegin", document.createElement("hr"));
                }     

            }
        )
    </script>
</head>
<body>
    <h1>All Post</h1>
    <div id="newPosts">

    </div>
    <div id="postContent">

    </div>
   
</body>

</html>

home/templates/home/post/allPosts2.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Posts</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <h1>All the posts</h1>

    <script>
        var roomName = JSON.parse(
                "0"
            );

        var socket = new WebSocket(
            "ws://"
            +window.location.host+
            "/home/some/"
            +roomName
        );

        socket.onopen = function() {
                
        }
        function k() {
            socket.send("sjsjs");
        }

        socket.onmessage = function(event) {
                console.log(event);
                console.log(event.data);
            }

    </script>
    
</body>
</html>

home/templates/home/post/allThePosts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All Posts</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
    <h1>All the posts</h1>
    <div id="posts">
    </div>
    <script>
        var indexGen = -1;
        $.get(
            "{% url 'home:getAllUserPosts' %}",
            function(data, status) {
                if (status == "success") {
                    for (var index in data) {
                        console.log(data[index]);
                        buildPost(data[index]);
                    }
                    checkLastPost();
                }
            }
        )

        function checkLastPost() {
            $.post(
                "{% url 'home:getLastPost' %}",
                {
                    "index": indexGen.toString()
                },
                function(data, status) {
                    if (status == "success") {
                        if (data["new"] == "true") {
                            buildPost(data["data"]);
                        }
                        console.log(data);
                        setTimeout(
                            function() {
                                checkLastPost();
                            },
                            3000
                        );
                        console.log(indexGen)
                    }
                }
            )

        }

        function buildPost(data) {
            var postsBody = document.getElementById("posts");

            var username = document.createElement("p");
            var content = document.createElement("p");
            var creationDate = document.createElement("p");

            var sU = document.createElement("strong");
            sU.appendChild(document.createTextNode("username: "))

            var sC = document.createElement("strong");
            sC.appendChild(document.createTextNode("content: "))

            var sCD = document.createElement("strong");
            sCD.appendChild(document.createTextNode("creationDate: "))

            username.appendChild(sU);
            content.appendChild(sC);
            creationDate.appendChild(sCD);

            username.appendChild(document.createTextNode(data["username"]));
            content.appendChild(document.createTextNode(data["content"]));
            creationDate.appendChild(document.createTextNode(data["creationDate"]));

            postsBody.appendChild(username);
            postsBody.appendChild(content);
            postsBody.appendChild(creationDate);
            postsBody.appendChild(document.createElement("hr"))

            if (document.body.scrollHeight-window.scrollY <= 744+70) {
                window.scrollTo(0, document.body.scrollHeight);
            }

            console.log(document.body.scrollHeight-window.scrollY);
            indexGen ++;
        }

    </script>
</body>
</html>

home/templates/home/post/jsjs.html
<!-- chat/templates/chat/room.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <textarea id="chat-log" cols="100" rows="20"></textarea><br>
    <input id="chat-message-input" type="text" size="100"><br>
    <input id="chat-message-submit" type="button" value="Send">
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/some/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
</body>
</html>

home/templates/home/post/postContent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Post Content</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        function submit() {
            $.post(
                "{% url 'home:newPost' %}",
                {
                    "content": document.getElementById("content").value
                },
                function(data, status) {
                    if (status == "success") {
                        document.getElementById("success").innerText = data;
                        setTimeout(
                            function() {
                                document.getElementById("success").innerText = "";
                            },
                            1000
                        )
                    }
                }
            )
        }
    </script>
</head>
<body>
    <h1>Post Content</h1>
    <textarea name="" id="content" cols="40" rows="6" placeholder="Put some content here" maxlength="254" style="font-family: 'Times New Roman', Times, serif;"></textarea>
    <br>
    <button type="button" onclick="submit()">submit</button>
    <br>
    <p id="success" style="color: red;"></p>
    <br>
    <a href="{% url 'home:allPosts' %}">See all posts</a>
</body>
</html>