home/urls.py
from django.urls import path
from . import views

app_name = "home"
urlpatterns = [
    path('', views.index, name='home'),
    
    #ajax
    path("ajax", views.ajaxMain, name="ajaxMain"),
    path("ajax/ajax", views.ajax, name="ajax"),
    path("ajax/ajaxjq", views.ajaxjq, name="ajaxjq"),
    path("ajax/ajaxjqcsrf", views.ajaxjqcsrf, name="ajaxjqcsrf"),
    path("response/<str:letter>", views.response, name="response"),
    path("post/response", views.responsePost, name="responsePost"),

    #misc
    path("space", views.space, name="space"),
    path("download", views.download, name="download"),

    #login
    path("accounts/signUp", views.signUp, name="signUp"),
    path("check/checkNewUser", views.checkNewUser, name="checkNewUser"),

    path("accounts/logIn", views.logIn, name="logIn"),
    path("check/logInCheck", views.logInCheck, name="logInCheck"),

    path("accounts/data", views.accountData, name="accountData"),

    path("check/checkLogOut", views.logOutCheck, name="logOutCheck"),

    path("accounts/changePassword", views.changePassWord, name="changePassWord"),
    path("check/passWord", views.validateNewPassword, name="validateNewPassword"),

    path("accounts/profilePic", views.profilePic, name="profilePic"),
    path("check/addProfilePic", views.addProfilePic, name="addProfilePic"),

    path("check/changeUserDescription", views.changeUserDescription, name="changeUserDescription"),
    path("check/delete", views.deleteUser, name="deleteUser"),
    #path("check/getDescription", views.getDescription, name="getDescription"),


    #post
    path("post/postContent", views.postContent, name="postContent"),
    path("check/newPost", views.newPost, name="newPost"),

    path("post/All/", views.allPosts, name="allPosts"),
    path("post/getAll", views.getAllUserPosts, name="getAllUserPosts"),
    path("post/getLast", views.getLastPost, name="getLastPost"),

    #chat
    path("chat", views.chatAll, name="chatAll"),
    path("chat/<str:room_name>/", views.room, name="room"),

    #attack
    path("attack/csrf", views.csrfAttack, name="csrfAttack"),

    path("friends/sendFriendRequest", views.sendFriendRequest, name="sendFriendRequest"),
    path("friends/getUserList", views.getUserList, name="getUserList"),
    path("friends/friendRequest", views.friendRequest, name="friendRequest"),
    path("friends/checkFriendRequest", views.checkFriendRequest, name="checkFriendRequest"),
    path("friends/getFriendRequest", views.getFriendRequest, name="getFriendRequest"),
    path("friends/acceptFriendRequest", views.acceptFriendRequest, name="acceptFriendRequest"),
    path("friends/allMyFriends", views.allMyFriends, name="allMyFriends"),
    path("friends/getFriends", views.getFriends, name="getFriends"),
    path("friends/removeFriend", views.removeFriend, name="removeFriend"),
    path("friends/firendProfile/<str:username>", views.firendProfile, name="firendProfile"),

    #chat
    path("userChat/<str:chatId>", views.chat, name="chat"),
    path("userChat/<str:username1>/<str:username2>", views.chatFriendToFriend, name="chatFriendToFriend"),
    path("initChat/<str:chatId>", views.initChat, name="initChat"),
]

myServer1/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

urlpatterns = [
    #app
    path("home/", include("home.urls")),
    #favicon
    path('favicon.ico/', RedirectView.as_view(url=staticfiles_storage.url('favicon.ico'))),
    #admin
    path('admin/', admin.site.urls),
]

home/models.py
from django.db import models
from django.utils import timezone

# Create your models here.

def dAllUsers():
    for user in User.objects.all():
        user.delete()

def dAllPosts():
    for user in UserPost.objects.all():
        user.delete()

def dAllFriends():
    for user in UserFriends.objects.all():
        user.delete()

def dAllRF():
    for user in FriendRequest.objects.all():
        user.delete()

def dAllChat():
    for user in Chat.objects.all():
        user.delete()

def dAllMessage():
    for user in Message.objects.all():
        user.delete()


class User(models.Model):
    username = models.CharField(max_length=254)
    password = models.CharField(max_length=254)
    creationDate = models.DateTimeField()
    profilePic = models.FileField(upload_to="static/upload/profilePic/", default="static/upload/profilePic/default.jpg")
    description = models.CharField(max_length=254, default="There is no description here")
    friends = models.ManyToManyField("UserFriends")
    friendRequest = models.ManyToManyField("FriendRequest")    

    def delete(self):
        for friend in self.friends:
            friend.delete()

        for friendRequest in self.friendRequest:
            friendRequest.delete()
        super().delete()

    def __str__(self):
        #return f"username: {self.username}, password: {self.password}, creationDate: {self.creationDate}, description: {self.description}, profilePic: {self.profilePic.url}"
        return f"""
(
    username: {self.username}, 
    password: {self.password}, 
    creationDate: {self.creationDate}, 
    description: {self.description}, 
    profilePic: {self.profilePic.url},
    friends: {self.friends.all().values_list("username", flat=True)}
    friendRequest: {self.friendRequest.all().values_list("username", flat=True)}
)
""".replace("(", "{").replace(")", "}")


class UserFriends(models.Model):
    username = models.CharField(max_length=254)
    creationDate = models.DateTimeField()

    def __str__(self):
        return f"username: {self.username}, creationDate: {self.creationDate}"


class FriendRequest(models.Model):
    username = models.CharField(max_length=254)
    creationDate = models.DateTimeField()

    def __str__(self):
        return f"username: {self.username}, creationDate: {self.creationDate}"

    @staticmethod
    def sendFriendRequest(fromUser, toUser):
        friendCheck = User.objects.filter(username=toUser).get().friends.filter(username=fromUser)
        if friendCheck.exists():
            return "This user is already your friend"
        userTo = User.objects.filter(username=toUser)
        if userTo.exists():
            if not User.objects.filter(username=toUser).get().friendRequest.filter(username=fromUser).exists():
                userDes = userTo.get()
                friendRequest = FriendRequest(username=fromUser, creationDate=timezone.now())
                friendRequest.save()

                userDes.friendRequest.add(friendRequest)
                userDes.save()

            return "Friend request sended successfully"

        return "Username does not exists"


class UserPost(models.Model):
    username = models.CharField(max_length=254)
    content = models.CharField(max_length=254)
    creationDate = models.DateTimeField()

    def __str__(self):
        return f"""
(
    username: {self.username}, 
    content: {self.content}, 
    creationDate: {self.creationDate}
)
""".replace("(", "{").replace(")", "}")

class Chat(models.Model):
    chatId = models.CharField(max_length=508)
    messages = models.ManyToManyField("Message")
    creationDate = models.DateTimeField()

    def __str__(self):
        return f"chatId: {self.chatId}, messages: {self.messages.all()}"


class Message(models.Model):
    user = models.ManyToManyField("User")
    content = models.CharField(max_length=254)
    creationDate = models.DateTimeField()

    def __str__(self):
        return f"user: {self.user}, creationDate: {self.creationDate}, content: {self.content}"


home/views.py
import json, time
from django.shortcuts import render, redirect
from django.core.files.storage import default_storage
from django.http import HttpResponse, JsonResponse, Http404
from django.template import loader
from django.views.decorators.csrf import csrf_protect, csrf_exempt
from django.utils import timezone
from django.core.files import File
from django import db
from . import urls, models, consumers

# Create your views here.

def index(request):
    template = loader.get_template("home/index.html")
    return HttpResponse(template.render())

def ajaxMain(request):
    """
    print(urls.urlpatterns)

    for patter in urls.urlpatterns:
    """
    return HttpResponse(
        render(
            request, 
            "home/ajaxMain.html",
            context={
                "myList": ["ajax", "ajaxjq", "ajaxjqcsrf", "home"]
            }
        )
    )

def ajax(request):
    template = loader.get_template("home/ajax/ajax.html")
    return HttpResponse(template.render())

@csrf_exempt
def ajaxjq(request):
    return HttpResponse(render(request, "home/ajax/ajaxjq.html"))

def ajaxjqcsrf(request):
    template = loader.get_template("home/ajax/ajaxjqcsrf.html")
    return HttpResponse(template.render())

def download(request):
    template = loader.get_template("home/download.html")
    return HttpResponse(template.render())

def space(request):
    template = loader.get_template("home/space.html")
    return HttpResponse(template.render())

def response(request, letter):
    a = list()

    a.append("Anna")
    a.append("Brittany")
    a.append("Cinderella")
    a.append("Diana")
    a.append("Eva")
    a.append("Fiona")
    a.append("Gunda")
    a.append("Hege")
    a.append("Inga")
    a.append("Johanna")
    a.append("Kitty")
    a.append("Linda")
    a.append("Nina")
    a.append("Ophelia")
    a.append("Petunia")
    a.append("Amanda")
    a.append("Raquel")
    a.append("Cindy")
    a.append("Doris")
    a.append("Eve")
    a.append("Evita")
    a.append("Sunniva")
    a.append("Tove")
    a.append("Unni")
    a.append("Violet")
    a.append("Liza")
    a.append("Elizabeth")
    a.append("Ellen")
    a.append("Wenche")
    a.append("Wendy")
    a.append("Vicky")
    a.append("Monika")
    a.append("Mariana")
    a.append("Maria")
    a.append("Martha") 

    names = list()
    for name in a:
        if name[0].lower() == letter.lower():
            names.append(name)

    return HttpResponse("no suggestion" if len(names) == 0 else ", ".join(names))

@csrf_exempt
def responsePost(request):
    a = list()

    a.append("Anna")
    a.append("Brittany")
    a.append("Cinderella")
    a.append("Diana")
    a.append("Eva")
    a.append("Fiona")
    a.append("Gunda")
    a.append("Hege")
    a.append("Inga")
    a.append("Johanna")
    a.append("Kitty")
    a.append("Linda")
    a.append("Nina")
    a.append("Ophelia")
    a.append("Petunia")
    a.append("Amanda")
    a.append("Raquel")
    a.append("Cindy")
    a.append("Doris")
    a.append("Eve")
    a.append("Evita")
    a.append("Sunniva")
    a.append("Tove")
    a.append("Unni")
    a.append("Violet")
    a.append("Liza")
    a.append("Elizabeth")
    a.append("Ellen")
    a.append("Wenche")
    a.append("Wendy")
    a.append("Vicky")
    a.append("Monika")
    a.append("Mariana")
    a.append("Maria")
    a.append("Martha") 

    names = list()
    for name in a:
        if name[0].lower() == request.POST.dict()["letter"].lower():
            names.append(name)
            
    return HttpResponse("no suggestion" if len(names) == 0 else ", ".join(names))


@csrf_exempt
def signUp(request):
    return render(request, "home/accounts/signUp.html")

@csrf_exempt
def checkNewUser(request):
    post = request.POST

    username = post.get("username")
    password = post.get("password")

    if username == "":
        return HttpResponse("Ivalid blank username")
    print("username")

    if password == "":
        return HttpResponse("Ivalid blank password")
    print("password")

    if username.replace(" ", "") == "":
        return HttpResponse("usernames cannot contain spaces")
    print("username space")

    if " " in password:
        return HttpResponse("passwords cannot contain spaces")
    print("password space")

    if models.User.objects.filter(username=username).exists():
        return HttpResponse("The username already exists")
    print("username used")

    if len(password) < 8:
        return HttpResponse("The password must be at least 8 characters long")
    print("passwordlen")

    user = models.User(username=username, password=password, creationDate=timezone.now())
    user.save()
    print("username saved")

    # no puede ser == ""
    # el nombre de usuario no debe estar usado
    # la contraseña de tener mas de 8 caracteres

    # si todo esta bien, se procede a la siguiente página

    # si algo esta mal, se devuelve que esta mal
    response = HttpResponse("True")
    response.set_cookie("username", username)
    response.set_cookie("password", password)
    return response

@csrf_exempt
def accountData(request):
    print(request.COOKIES)
    if "username" in request.COOKIES and "password" in request.COOKIES:
        user = models.User.objects.filter(username=request.COOKIES["username"])
        if user.exists():
            if user.get().password == request.COOKIES["password"]:
                return render(
                    request, 
                    "home/accounts/accountData.html", 
                    context={
                        "username": request.COOKIES["username"],
                        "password": request.COOKIES["password"],
                        "creationDate": user.get().creationDate,
                        "description": user.get().description,
                        "profilePic": user.get().profilePic.url
                    }
                )

    return redirect("home:logIn")

@csrf_exempt
def changePassWord(request):
    return render(request, "home/accounts/changePassword.html")

@csrf_exempt
def validateNewPassword(request):
    post = request.POST
    oldPassword = post.get("oldPassword")
    newPassword = post.get("newPassword")
    newPasswordCon = post.get("newPasswordCon")

    if oldPassword == "" or newPassword == "" or newPasswordCon == "":
        return HttpResponse("Ivalid blank password")

    if " " in oldPassword or " " in newPassword or " " in newPasswordCon:
        return HttpResponse("passwords cannot contain spaces")

    if len(oldPassword) < 8 or len(newPassword) < 8 or len(newPasswordCon) < 8:
        return HttpResponse("The password must be at least 8 characters long")

    if "username" in request.COOKIES and "password" in request.COOKIES:
        username = request.COOKIES["username"]
        user = models.User.objects.filter(username=username)

        if user.exists():
            if user.get().password == oldPassword:
                if newPassword == newPasswordCon:
                    userpass = user.get()
                    userpass.password = newPassword
                    userpass.save()
                    response = HttpResponse("Password changed succesfully")
                    response.set_cookie("password", newPassword)
                    return response

                return HttpResponse("The new password does not match")
            
            return HttpResponse("Invalid old password")

        return HttpResponse("The user does not exists")

    return redirect("home:logIn")

@csrf_exempt
def logIn(request):
    return render(request, "home/accounts/logIn.html")

@csrf_exempt
def logInCheck(request):
    post = request.POST

    username = post.get("username")
    password = post.get("password")

    if username == "":
        return HttpResponse("Ivalid blank username")
    print("username")

    if password == "":
        return HttpResponse("Ivalid blank password")
    print("password")

    if username.replace(" ", "") == "":
        return HttpResponse("usernames cannot contain spaces")
    print("username space")

    if " " in password:
        return HttpResponse("passwords cannot contain spaces")
    print("password space")

    if len(password) < 8:
        return HttpResponse("The password must be at least 8 characters long")
    print("passwordlen")

    user = models.User.objects.filter(username=username)
    if user.exists():
        if user.get().password == password:
            response = HttpResponse("True")
            response.set_cookie("username", username)
            response.set_cookie("password", password)
            return response

        else:
            return HttpResponse("Incorrect Password")

    else:
        return HttpResponse("The username does not exists")

def logOutCheck(request):
    response = HttpResponse("Log Out Succesfuly")
    response.delete_cookie("username")
    response.delete_cookie("password")
    return response


def deleteUser(request):
    response = redirect("home:home")
    if "username" in request.COOKIES and "password" in request.COOKIES:
        username = request.COOKIES["username"]
        password = request.COOKIES["password"]

        user = models.User.objects.filter(username=username)
        if user.exists() and user.get().password == password:
            user.delete()
            response.delete_cookie("username")
            response.delete_cookie("password")

    return response

@csrf_exempt
def csrfAttack(request):
    return render(request, "home/attac/csrf.html")

@csrf_exempt
def profilePic(request):
    return render(request, "home/accounts/profilePic.html")

@csrf_exempt
def addProfilePic(request):

home/templates/home/friends/allMyFriends.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Friends</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/basic.js' %}"></script>
    <script>
        var content = [];
        function getFriends() {
            $.get(
                "{% url 'home:getFriends' %}",
                function(data, status) {
                    if (status == "success") {
                        console.log(data);
                        data["data"].forEach(element => {
                            buildUser(element);
                        });
                    }
                }
            )
        }

        function removeFriend(username) {
            if (confirm("Did yuo want to remove this friend from your firend list")) {
                $.post(
                    "{% url 'home:removeFriend' %}",
                    {
                        "username": username
                    },
                    function(data, status) {
                        if (status == "success") {
                            var success = document.getElementById(username);
                            success.innerHTML = '<p style="color: red;">'+data+'</p>';
                            setTimeout(
                                function() {
                                    success.innerText = "";
                                    console.log(true);
                                    content.forEach(element => {
                                        if (element.id == username) {
                                            element.remove();
                                        }
                                    });
                                },
                                3000
                            );
                            console.log(true);
                            
                        }
                    }
                );
            }
        }

        function goToChat(username2) {
            window.location.href = "/home/userChat/"+getCookie("username")+"/"+username2;
        }

        function seeProfile(username) {
            window.location.href = "/home/friends/firendProfile/"+username;
        }

        function buildUser(data) {
            var username = data[0];
            var profilePic = data[1];
            var div = document.getElementById("userList");

            var placeholder = document.createElement("div");
            div.appendChild(placeholder);

            var button = '<button onclick="seeProfile(\'UUU\')">See profile</button><button onclick="goToChat(\'UUU\')">Chat</button><button onclick="removeFriend(\'UUU\', \'true\')">Remove Friend</button>';
            button = button.replace(/UUU/g, username);

            var inner = '<h2 style="color: #000000;"><img style="float: left;" src="/SSS" alt="profilePic" width="93" height="93" /><hr> UUU</h2>BBB';
            inner = inner.replace(/UUU/g, username);
            inner = inner.replace(/SSS/g, profilePic);
            inner = inner.replace(/BBB/g, button);

            placeholder.innerHTML = inner;
            placeholder.id = username;
            content.push(placeholder);
        }

        $(
            function() {
                getFriends();
            }
        )
    </script>
</head>
<body>
    <h1>Friends</h1>
    <div id="userList"></div>
</body>
</html>

home/templates/home/friends/checkFriendRequest.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Friend Requests</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/basic.js' %}"></script>
    <script>
        var content = [];
        function getFriendRequest() {
            $.get(
                "{% url 'home:getFriendRequest' %}",
                function(data, status) {
                    if (status == "success") {
                        console.log(data);
                        data["data"].forEach(element => {
                            buildUser(element);
                        });
                    }
                }
            )
        }

        function buildUser(data) {
            var username = data[0];
            var profilePic = data[1];
            var div = document.getElementById("userList");

            var placeholder = document.createElement("div");
            div.appendChild(placeholder);

            var button = '<button onclick="acceptFriendRequest(\'UUU\', \'true\')">Accept Friend Request</button><button onclick="acceptFriendRequest(\'UUU\', \'false\')">Deny Friend Request</button>';
            button = button.replace(/UUU/g, username);

            var inner = '<h2 style="color: #000000;"><img style="float: left;" src="/SSS" alt="profilePic" width="93" height="93" /><hr> UUU</h2>BBB';
            inner = inner.replace(/UUU/g, username);
            inner = inner.replace(/SSS/g, profilePic);
            inner = inner.replace(/BBB/g, button);

            placeholder.innerHTML = inner;
            placeholder.id = username;
            content.push(placeholder);
        }

        function acceptFriendRequest(username, accepted) {
            $.post(
                "{% url 'home:acceptFriendRequest' %}",
                {
                    "accepted": accepted,
                    "username": username
                },
                function(data, status) {
                    if (status == "success") {
                        var success = document.getElementById(username);
                        success.innerHTML = '<p style="color: red;">'+data+'</p>';
                        setTimeout(
                            function() {
                                success.innerText = "";
                                console.log(true);
                                content.forEach(element => {
                                    if (element.id == username) {
                                        element.remove();
                                    }
                                });
                            },
                            3000
                        );
                        console.log(true);
                        
                    }
                }
            );
        }

        $(
            function() {
                getFriendRequest();
            }
        )
    </script>
</head>
<body>
    <h1>Friend Requests</h1>
    <div id="userList"></div>
</body>
</html>

home/templates/home/friends/seeProfile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ username }}</title>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
	<script>
		$(
			function() {
				var br = document.getElementById("description");
				br.innerHTML = br.innerHTML.replace(/\n/g, "<br>");
			}
		);
	</script>
</head>
<body>
    <img src="{{ profilePic }}" alt="profilePic" style="width: 300px; height: 300px;">
    <h2>{{ username }}</h2>
    <p>Joined at: {{ creationDate }}</p>
    
    <p>Description:</p>
    <p id="description">{{ description }}</p>
    <a href="{% url 'home:allMyFriends' %}">Go back to friend page</a> 
</body>
</html>

home/templates/home/friends/sendFriendRequest.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Search</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="{% static 'js/basic.js' %}"></script>
    <script>
        var content = [];

        $(
            function() {
                sendByEnter(
                    document.getElementById("username"), 
                    searchUser
                );
            }
        )

        function searchUser() {
            $.post(
                "{% url 'home:getUserList' %}",
                {
                    "username": document.getElementById("username").value
                },
                function(data, status) {
                    if (status == "success") {
                        cleanContent();
                        console.log(data);
                        if (data["userList"].length != 0) {
                            data["userList"].forEach(element => {
                                buildUser(element);
                            });
                        } else {
                            noResults();
                        }
                    }
                }
            )
        }

        function noResults() {
            var div = document.getElementById("userList");
            var p = document.createElement("p");
            p.appendChild(document.createTextNode("Thre's no results"));
            content.push(p);
            div.appendChild(p);
        }

        function buildUser(data) {
            var username = data[0];
            var profilePic = data[1];
            var div = document.getElementById("userList");

            var placeholder = document.createElement("div");
            div.appendChild(placeholder);

            var button = '<button onclick="sendFriendRequest(\'UUU\')">Send Friend Request</button>';
            button = button.replace(/UUU/g, username);

            var inner = '<h2 style="color: #000000;"><img style="float: left;" src="/SSS" alt="profilePic" width="93" height="93" /><hr> UUU</h2>BBB<p id="UUU" style="color: red;"><p>';
            inner = inner.replace(/UUU/g, username);
            inner = inner.replace(/SSS/g, profilePic);
            inner = inner.replace(/BBB/g, button);

            placeholder.innerHTML = inner;
            content.push(placeholder);
        }

        function cleanContent() {
            content.forEach(element => {
                element.remove();
            });
        }

        function sendFriendRequest(username) {
            $.post(
                "{% url 'home:friendRequest' %}",
                {
                    "username": username
                },
                function(data, status) {
                    if (status == "success") {
                        var success = document.getElementById(username);
                        success.innerText = data;
                        setTimeout(
                            function() {
                                success.innerText = "";
                                console.log(true);
                            },
                            3000
                        );
                        console.log(true);
                    }
                }
            )
        }
    </script>
</head>
<body>
    <input type="text" name="" id="username" placeholder="Search user">
    <br>
    <button type="button" onclick="searchUser()">search</button>
    <div id="userList"></div>
</body>
</html>